---
title: "Raceway Image Capture Standard Operating Procedure"
author: "Lily Gullett"
date: "2023-09-29"
output:
  html_document:
    theme: flatly
    code_folding: show
    toc: yes
    toc_depth: 3
    toc_float: yes
  pdf_document:
    toc: no
    toc_depth: '3'
---


```{r, setup, include = FALSE}
knitr::opts_chunk$set(warning = FALSE, fig.align = 'left')
library(magrittr)
```

<!-- if updating, make sure you change name below -->
### Last Updated: Lily Gullett, `r Sys.Date() %>% format(format="%B %d, %Y")`


## Overview

Contained in this document is the Standard Operating Procedure for raceway image capture using an Olympus TG-6 for Mote Marine Laboratory's small-scale Structure-from-Motion photogrammetry pipeline for capturing ex situ coral recruits. Additional Standard Operating Procedures for other aspects within the photogrammetric pipeline can be found [here](https://github.com/Mote-Coral-Reef-Restoration/MoteSOPs).


### **Raceway Image Capture**
***

**Note:** 
The methods we used changed over time slightly due to increased visibility of recruits. This is what worked for us, however you may need to tailor these to your situation.
No skeleton deposited, hardly visible to human eye: Camera was kept a distance of ~6.5 centimeters from rack. For our racks, it helped to try to keep 3 rack holes (4.5cm) vertically and 4 rack holes (6cm) horizontally in the frame to ensure height stays consistent.
Skeleton being deposited, more visible to human eye: Camera was kept a distance of ~8cm from rack. For our racks, it helped to try to keep 4 rack holes (6cm) vertically and 5 rack holes (7.5cm) horizontally in the frame to ensure height stays consistent. When they begin to grow their polyps and produce secondary polyps and it becomes difficult to define their borders later in the pipeline as well as distinguish between different recruits. To combat this, we used a baster to make them withdraw their polyps before and during each scan as needed. 


1. Before you begin, procure a waterproof white light (example: Suptig Diving Light) and if possible, attach it to your camera. Then, ensure your camera has the correct settings. Settings can be found [here]().

2. Add scale bars to your rack. Glue the scale bars to plugs and allow them to cure and soak before doing a scan. When gluing scale bars it is advised that you cut a standard ruler on waterproof paper in half (15 cm) and put the plugs in the egg crate at the desired distance apart so that you ensure they remain flat during scans. The scale bars should be placed around each outside edge of your group of plugs. If you have Agisoft Metashape Pro there are printable markers under the Tools &rarr Markers &rarr Print Markers... which should be glued to plugs, allowed to cure and soak, and distributed at all four corners and in the middle of your group of plugs containing recruits. These markers assist the software in generating products downstream however they are not necessary. 
 
3. Position your rack relatively isolated within the raceway over sheets of waterproof paper to create a white background. Having other racks of coral in the periphery of the frame could potentially affect downstream model generation. Turn off pumps and flow if they are disturbing the surface of the water in order to avoid unnecessary shadows. 

4. Place the camera in the water, tilt the lens upward to remove any bubbles obscuring the lens. Position the camera to maintain the same altitude throughout the image capture process and ensure both level bars are green. Depending on the size of the recruits the altitude of your camera should change. 

5. Turn on your white light and position it at a 45 degree angle relative to your camera. Look through the viewfinder to make sure that the subject is illuminated and that shadows are reduced as much as possible. When on the edges of frame light may need to be tilted more toward 90 degrees to reduce shadows.

6. Position the camera face down and start at the bottom left or right corner of the subject. Make sure that <20% of the subject is in frame, with the remaining portion of your viewfinder being taken up by raceway.

7. Press the shutter button to begin the image capture sequence. Every time the camera snaps a photo, move the camera forward in a lawnmower pattern. It is important to maintain 70-80% overlap between subsequent photos and passes. Keep the camera oriented straight down throughout the scan.

Note: The camera is set to capture 299 consecutive photos. If at anytime you need to stop filming, simply press the "Menu" button. If your pass is greater than 299 photos, simply just press the shutter button again to restart the interval sequence.


