---
title: "Metashape Imagery Processing Standard Operating Procedure"
author: "Lily Gullett"
date: "2023-09-28"
output:
  html_document:
    theme: flatly
    code_folding: show
    toc: yes
    toc_depth: 3
    toc_float: yes
  pdf_document:
    toc: no
    toc_depth: '3'
---

```{r, setup, include = FALSE}
knitr::opts_chunk$set(warning = FALSE, fig.align = 'left')
library(magrittr)
```

<!-- if updating, make sure you change name below -->
### Last Updated: Lily Gullett, `r Sys.Date() %>% format(format="%B %d, %Y")`


## Overview

Contained in this document is the Standard Operating Procedure for model generation using Agisoft Metashape for Mote Marine Laboratory's small-scale Structure-from-Motion photogrammetry pipeline. Additional Standard Operating Procedures for other aspects within the photogrammetric pipeline can be found [here](https://github.com/Mote-Coral-Reef-Restoration/MoteSOPs).


### **Metashape Image Processing**
***

1.	Open Metashape and select Preferences. Under the GPU tab, make sure any available GPU devices are selected.

2.  Select the Add Photos icon in the Workspace window. Navigate to your working directory and select all of the still images. Once imported, they will show up as a Chunk (set of photos). Save the project.

3.  If you used markers, select Tools, hover over Markers, and select Detect Markers. This will assist the software with the photo alignment process, however they are only available in Metashape Pro and are not necessary for generation. 

4.	Start the image alignment process by selecting Workflow, Align Photos. Set the Accuracy to High. This process may take some time, since it finds common points among the photos.

5.	Check the alignment by looking at the Photos window under View. Each photo will show up as a thumbnail; if it has aligned, you will see a check mark. You can also check the aligned photo placement in the sparse point cloud in the Model window. Select the Show Cameras icon to see where the program thinks they were taken. The blue camera icons should approximately match the path taken in the original video. Use each of the three colored axes on the model sphere to move in 3 dimensional space, and scroll to zoom in and out.
    a.	If all the photos aligned correctly, proceed to the next step.
    b.	If some did not align properly, you can select the particular photos and Select Align Photos again. Alternatively, you can realign all of the photos, go to Processes: Align Photos and make sure that "Reset Current Alignment" is deselected (this will start everything from scratch and will take longer)

11.	Select Resize Region. Ensure that the Region (the gray box) encompasses the entirety of your model (make sure to check the X, Y, and Z plane). The remaining steps only take into account what is located inside the Region. This is also a good time to remove any outliers or points you do not want in your model. You can do this by resizing the region or by using the selection tool, highlighting the undesirable points, and pressing delete.

12.	Once enough photos are aligned, select Build Dense Cloud under Workflow. Set the Quality to High and start the process.

13.	Once finished, you should have a decent representation of the model features built from many small points.
    a.	Check all angles of the point cloud, looking for aberrant features (“floaters”).
    b.	Since these will not be well represented in the finished model, they should be removed. Position the model so that the problem features are isolated from the other parts of the model (nothing behind the features). Use the Rectangle Selection tool on the toolbar to highlight any offending points, and select the Delete Selection tool on the toolbar.
    c.	Don’t worry if this creates small gaps, as they will be filled in when the mesh is made. You do, however, have to remove all the problem features at this stage, otherwise you will have holes in your mesh.
    d. To ensure a cleaner looking dense cloud select Tools &rarr Dense Cloud &rarr Filter by Confidence. Then set the Max confidence to 1 and click OK. After you have done this the dense cloud should show up with fewer points on it, many that may be outliers. Using the free form selection tool (next to the Navigation tool) select all points and delete. Then navigate to Tools &rarr Dense Cloud &rarr Reset Filter. Once you reset the filter the original dense cloud should return with less erratic points. 

14.	Start the Build Mesh process from the Workflow menu. Change the Face Count to 1,000,000 for high accuracy. You can set the mesh higher, however adding the texture automatically decimates the mesh to 1,000,000 face count.
    a.	For High-Throughput: Select Workflow, Batch Processes. Load the second batch process you made called “Batch Texture.” Click OK. (This batch process combines steps 13 and 14, which are relatively quick, use the QA/QC procedures below and rerun as normal if needed.)
    b.	Now you should have a smoothed version of the point cloud. Check for any lingering problem features.
    c.	If anything is found, switch back to the Dense Point Cloud using the button on the toolbar, remove them as described above, and regenerate the mesh.

15.	Start the Build Texture process from the Workflow menu, which may take another 5–10 minutes. Once completed, the photo texture will be mapped to the 3D model.

16. Once you have a mesh and texture, select Build Orthomosaic from the Workflow menu.   
    * Type: Planar
    * Projection Plane
    * Top XY OR Markers (if capable)
    * Surface: Mesh  
    * Blending Mode: Mosaic
    * Max. dimensions (pix): 20,000


16.	Export the orthomosaic by selecting File &rarr Export &rarr Export Orthomosaic.

**Note:** The above steps are for single model generation however if you want to do High-Throughput there is an additional Standard Operating Procedure that can be found [here](https://github.com/Mote-Coral-Reef-Restoration/MoteSOPs/smallScaleSfm/3.metashapeImageryProcessingSOP).