---
title: "Raceway Image Capture Standard Operating Procedure"
author: "Ian Combs"
date: "2023-06-16"
output:
  html_document:
    theme: flatly
    code_folding: show
    toc: yes
    toc_depth: 3
    toc_float: yes
  pdf_document:
    toc: no
    toc_depth: '3'
---


```{r, setup, include = FALSE}
knitr::opts_chunk$set(warning = FALSE, fig.align = 'left')
library(magrittr)
```

<!-- if updating, make sure you change name below -->
### Last Updated: Ian Combs, `r Sys.Date() %>% format(format="%B %d, %Y")`


## Overview

Contained in this document is the Standard Operating Procedure for raceway image capture using an Olympus TG-6 for Mote Marine Laboratory's small-scale Structure-from-Motion photogrammetry pipeline. Additional Standard Operating Procedures for other aspects within the photogrammetric pipeline can be found [here](https://github.com/Mote-Coral-Reef-Restoration/MoteSOPs).


### **Raceway Image Capture**
***

1. Before you begin, ensure your camera has the correct settings. Settings can be found [here](). Position your subject (rack of coral fragments, whole coral piece, or coral fragments in starboard) relatively isolated within the raceway. Having other racks of coral in the periphery of the frame could potentially affect downstream model generation.

2. Place the camera in the water, tilt the lens upward to remove any bubbles obscuring the lens. Position the camera to maintain the same altitude throughout the image capture process.

3. Position the camera face down and start at the bottom left or right corner of the subject. Make sure that <20% of the subject is in frame, with the remaining portion of your viewfinder being taken up by raceway.

4. Press the shutter button to begin the image capture sequence. Every time the camera snaps a photo, move the camera forward in a lawnmower pattern. It is important to maintain 70-80% overlap between subsequent photos and passes. Keep the camera oriented straight down and do not change the orientation in between adjacent passes. At the end of the first set of passes, rotate the camera 90&deg; and complete another set of passes, continuing to take photos

Note: The camera is set to capture 200 consecutive photos. If at anytime you need to stop filming, simply press the "Menu" button. If your pass is greater than 200 photos, simply just press the shutter button again to restart the interval sequence.


